# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SberThree' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SberThree
  pod 'BaseTableViewKit', :git => 'https://github.com/MosMetro-official/BaseTableViewKit'
  # platform :ios, '8.0'
  pod 'SDWebImage', '~> 5.0'

end
